import pandas as pd

df1 = pd.DataFrame(columns=('INSURANCE', 'PAYER', 'STATUS', 'AMOUNT'))
class FindSubmit:
    def __init__(self, PayerID, InsCom):
        self.PayerID = PayerID
        self.InsCom = InsCom
        # df1 = pd.DataFrame(columns=('INSURANCE', 'PAYER', 'STATUS', 'AMOUNT'))
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df['NET7'])
        print(self.InsCom, self.PayerID, 'Submission', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['Paid'] == 'O'])
        df = (df['PaymentAmount'])
        print(self.InsCom, self.PayerID, 'Paid', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['Reject'] == 'O'])
        df = (df['NET7'])
        print(self.InsCom, self.PayerID, 'Reject', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['Pending'] == 'O'])
        df = (df[df['Days'] >= 46 ])
        df = (df['NET7'])
        print(self.InsCom, self.PayerID, 'Pending', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['Pending'] == 'O'])
        df = (df[df['Days'] <= 45 ])
        df = (df['NET7'])
        print(self.InsCom, self.PayerID, 'Process', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['PaymentNOT'] == 'O'])
        df = (df['PaymentAmount'])
        print(self.InsCom, self.PayerID, 'Paid_error', df.sum())
        df = pd.read_csv('submit.csv')
        df = (df[df['PayerID'] == self.PayerID])
        df = (df[df['PaymentNOT'] == "O"])
        df = (df['NET7'] - df['PaymentAmount'])
        print(self.InsCom, self.PayerID, 'reject_error', df.sum())

DAMAN = FindSubmit('INS026', 'DAMAN')
THIQA = FindSubmit('INS078', 'THIQA')
SAICO = FindSubmit('INS015', 'SAICO')
ADNIC = FindSubmit('INS017', 'ADNIC')
METLIFE = FindSubmit('INS013', 'METLIFE')
OMAN = FindSubmit('INS012', 'OMAN')
SAADA = FindSubmit('INS129', 'SAADA')

print(df1)